services:
  php:
    image: symfony-php-1
    user: "${USER_ID:-1000}:${GROUP_ID:-1000}"  # Zmiana z "www-data" na dynamiczne ID
    build:
      context: .
      dockerfile: Dockerfile
    container_name: symfony-php-1
    restart: unless-stopped
    working_dir: /app
    volumes:
      - .:/app
    environment:
      APP_ENV: dev
      DATABASE_URL: mysql://symfony:symfony@database:3306/symfony?serverVersion=8.0&charset=utf8mb4
      NPM_CONFIG_CACHE: /app/.npm
      NPM_CONFIG_PREFIX: /app/.npm
    depends_on:
      - database

  database:
    image: mysql:8.0
    container_name: symfony-mysql-1
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: symfony
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  nginx:
    image: nginx:latest
    container_name: symfony-nginx-1
    restart: unless-stopped
    volumes:
      - .:/app
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8000:80"
    depends_on:
      - php

  node:
    image: node:18
    container_name: symfony-node-1
    user: "1000:1000"  # Użyj UID i GID swojego użytkownika na hoście
    working_dir: /app
    volumes:
      - .:/app
    command: ["tail", "-f", "/dev/null"]

volumes:
  db_data: