# twig:
#     file_name_pattern: '*.twig'

# when@test:
#     twig:
#         strict_variables: true
twig:
    default_path: '%kernel.project_dir%/templates'
    globals:
        live_component: '@ux.live_component.twig.component_renderer'

twig_component:
    defaults:
        App\Twig\Component\: ~